version: 0.2


phases:
  install:
    runtime-versions:
      python: 3.10

  pre_build:
    commands:
      - pip install -r ./requirements.txt --upgrade
      - pip install -r ./requirements-dev.txt --upgrade

      - mkdir -p layer/python
      - pip install --target ./layer/python -r ./requirements.txt

      - docker login -u horietakehiro -p ${DOCKERHUB_PASSWORD}

  build:
    on-failure: ABORT
    commands:
      - export PYTHONPATH=`pwd`:`pwd`/src:`pwd`/tests/features:${PYTHONPATH}
      - export PATH=/root/.pyenv/versions/3.10.12/bin:${PATH}

      # run unit tests
      - python setup.py develop
      - cfn-docgen --version
      - pytest -v --junit-xml UnitTestReports.xml --cov=src --cov-report=xml ./src/

      # build docker images for bdd tests
      - VERSION=`python -c "from cfn_docgen import VERSION; print(VERSION)"`
      - docker build -t horietakehiro/cfn-docgen:${VERSION} -f ./deployments/Dockerfile ./

      # deploy serverless application for bdd tests
      - sam package
          --template-file deployments/serverless.yaml
          --output-template-file deployments/serverless.yaml.packaged
          --s3-bucket ${ARTIFACT_BUCKET}
          --s3-prefix serverless
      - sam deploy
          --template-file deployments/serverless.yaml.packaged
          --stack-name cfn-docgen-serverless-bdd
          --capabilities CAPABILITY_IAM
          --no-fail-on-empty-changeset
          --parameter-overrides ParameterKey=SourceBucketNamePrefix,ParameterValue=cfn-docgen-bdd
  
      # run bdd tests
      - behave tests/features/


  post_build:
    on-failure: ABORT
    commands:
      # publish python package
      - python setup.py sdist bdist_wheel
      - twine upload --repository pypi --username __token__ --password ${API_TOKEN} dist/*

      # push docker image
      - VERSION=`python -c "from cfn_docgen import VERSION; print(VERSION)"`
      - docker push horietakehiro/cfn-docgen:${VERSION}

      # publish serverless application
      - sam publish -t deployments/serverless.yaml.packaged  --region ${AWS_REGION}
      - AWS_ACCOUNT_ID=`aws sts get-caller-identity  | jq -r .Account`
      - aws serverlessrepo  put-application-policy
          --application-id arn:aws:serverlessrepo:${AWS_REGION}:${AWS_ACCOUNT_ID}:applications/cfn-docgen-serverless 
          --statements  Principals=*,Actions=Deploy

      # merge all changes to master branch
      - git checkout master
      - git rebase release
      - git push https://${GITHUB_TOKEN}@github.com/horietakehiro/cfn-docgen.git master


reports:
  UnitTestReports:
    files:
      - ./UnitTestReports.xml
    file-format: JUNITXML
  UnitTestCoverage:
    files:
      - ./coverage.xml
    file-format: COBERTURAXML

cache:
  paths:
    - /root/.cache/pip/**/*
    - layer/python/**/*
