AWSTemplateFormatVersion: 2010-09-09
Description: AWS resources for CI/CD piepeline

Metadata:
  CfnDocgen:
    Description: |
      1. code pipeline will be triggered when source repository branch `release` changes
      2. firstly, run all tests, and publish python package to pypi
      3. next, build serverless application and docker image and publish them
      4. finally, merge all changes on branch `release` with branch `master`

Parameters:
  AppName:
    Description: App name
    Type: String
    Default: cfn-docgen
  ApiTokenParamName:
    Description: Paramter name of api token for uploading a package to pypi  
    Type: String
  DockerHubPasswordParamName:
    Description: Paramter name of password for pushing image to DockerHub  
    Type: String
  GithubTokenParamName:
    Description: Parameter name of github access token
    Type: String
  ServerlessTestBucketName:
    Type: String

  SkipLongTest:
    Type: String
    Default: "1"
    AllowedValues:
      - "1"
      - "0"

Resources:

  SkipLongTextParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Name: !Sub /${AppName}/CICD/SKIP_LONG_TEST
      Type: String
      Value: !Ref SkipLongTest


  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  DockerContainerRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt BuildRole.Arn
            Action:
              - 'sts:AssumeRole'
      Description: Service Role for Codepipeline
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /


  BuildProject:
    Metadata:
      CfnDocgen:
        Properties:
          Environment:
            EnvironmentVariables:
              - API_TOKEN must be set at Parameter store in advance.
            Image: python3.10 is available only in standard:6.0
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      Description: Run tests and publish cfn-docgen as pypi package, docker image, and esrverless application 
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: DOCKERHUB_PASSWORD
            Type: PARAMETER_STORE
            Value: !Ref DockerHubPasswordParamName
          - Name: GITHUB_TOKEN
            Type: PARAMETER_STORE
            Value: !Ref GithubTokenParamName
          - Name: API_TOKEN
            Type: PARAMETER_STORE
            Value: !Ref ApiTokenParamName
          - Name: TEST_BUCKET_NAME
            Type: PLAINTEXT
            Value: !ImportValue cfn-docgen-test-bucket-name
          - Name: DEST_BUCKET_NAME
            Type: PLAINTEXT
            Value: !ImportValue cfn-docgen-test-bucket-name
          - Name: DEST_BUCKET_PREFIX
            Type: PLAINTEXT
            Value: documents/
          - Name: SERVERLESS_BUCKET_NAME
            Type: PLAINTEXT
            Value: !Ref ServerlessTestBucketName
          - Name: ARTIFACT_BUCKET_NAME
            Type: PLAINTEXT
            Value: !ImportValue cfn-docgen-artifact-bucket-name
          - Name: SKIP_LONG_TEST
            Type: PARAMETER_STORE
            Value: !Ref SkipLongTextParam
          - Name: DOCKER_CONTAINER_ROLE_ARN
            Type: PLAINTEXT
            Value: !GetAtt DockerContainerRole.Arn

        Image: aws/codebuild/standard:6.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      Name: !Sub ${AppName}-buildproject
      ServiceRole: !Ref BuildRole
      Source:
        # Auth: 
        #   SourceAuth
        BuildSpec: ./deployments/buildspec.yaml
        GitCloneDepth: 1
        Location: https://github.com/horietakehiro/cfn-docgen
        ReportBuildStatus: true
        # SourceIdentifier: 
        Type: GITHUB
      SourceVersion:  refs/heads/release
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
      Triggers:
        BuildType: BUILD
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/release
