AWSTemplateFormatVersion: 2010-09-09
Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub cfn-docgen-test-bucket-${AWS::AccountId}-${AWS::Region}
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub cfn-docgen-artifact-bucket-${AWS::AccountId}-${AWS::Region}
  PublishBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${ArtifactBucket}/*
            Principal:
              Service: serverlessrepo.amazonaws.com
            Condition:
              StringEquals:
                "aws:SourceAccount":
                  - !Ref AWS::AccountId
Outputs:
  TestBucketName:
    Value: !Ref TestBucket
    Export:
      Name: cfn-docgen-test-bucket-name
      
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: cfn-docgen-artifact-bucket-name