# https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

# env:
  # exported-variables:
    # - ARTIFACT_BUCKET
#     SAMPLING:
#     DOMAIN_NAME:
#     DOMAIN_OWNER:
#     REPOSITORY_NAME:


phases:

  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - docker login -u horietakehiro -p ${DOCKERHUB_PASSWORD}

  build:
    on-failure: ABORT
    commands:
      - docker build -t horietakehiro/cfn-docgen:latest .

  post_build:
    on-failure: ABORT
    commands:
      - docker push horietakehiro/cfn-docgen:latest


# reports:
#   UnitTestReports:
#     files:
#       - ./UnitTestReports.xml
#     file-format: JUNITXML
#   UnitTestCoverage:
#     files:
#       - ./coverage.xml
#     file-format: COBERTURAXML

# artifacts:
#   files:
#     - ./warnings.log
# cache:
#   paths:
#     - /root/.cfn-docgen/cache/*.json
#     - /root/.cache/pip/**/*

