# https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

# env:
  # exported-variables:
    # - ARTIFACT_BUCKET
#     SAMPLING:
#     DOMAIN_NAME:
#     DOMAIN_OWNER:
#     REPOSITORY_NAME:


phases:

  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - pip install -r ./requirements.txt
      - pip install -r ./requirements-test.txt

  build:
    on-failure: ABORT
    commands:
      - pytest -v --junit-xml UnitTestReports.xml --cov=cfn_docgen --cov-report=xml ./tests/
      - cat /root/.cfn-docgen/log/cfn-docgen.log | { grep WARN || true; } > ./warnings.log

  post_build:
    on-failure: ABORT
    commands:
      - python setup.py sdist bdist_wheel
      - twine upload --repository pypi --username __token__ --password ${API_TOKEN} dist/*


reports:
  UnitTestReports:
    files:
      - ./UnitTestReports.xml
    file-format: JUNITXML
  UnitTestCoverage:
    files:
      - ./coverage.xml
    file-format: COBERTURAXML

artifacts:
  files:
    - ./warnings.log
cache:
  paths:
    - /root/.cfn-docgen/cache/*.json
    - /root/.cache/pip/**/*

