AWSTemplateFormatVersion: 2010-09-09
Description: AWS resources for CI/CD piepeline

Parameters:
  AppName:
    Description: App name
    Type: String
    Default: cfn-docgen
  SamplingParamName:
    Description: Paramter name of sampling number of unittest
    Type: String
    Default: /cfn-docgen/sampling
  ArtifactRepositoryName:
    Description: Repository name of CodeArtifact
    Type: String
    Default: pypi
  ApiTokenParamName:
    Description: Paramter name of api token for uploading a package to pypi  
    Type: String
  SourceURL:
    Description: Source URL of github repository
    Type: String
    Default: https://github.com/horietakehiro/cfn-docgen.git
  BucketName:
    Description: S3 bucket name for uploading artifacts 
    Type: String
  SnsTopicArn:
    Description: Arn of sns topic  
    Type: String

Resources:

  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Policies:
        - PolicyName: get-parameter-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ssm:GetParameters
                Resource: '*'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: S3
        Location: !Ref BucketName
        Name: WarningLogs.log
        NamespaceType: BUILD_ID
        Path: BuildArtifacts
        Packaging: NONE
      Description: Run tests and upload artifacts to pypi
      BadgeEnabled: true
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: SAMPLING
            Type: PARAMETER_STORE
            Value: !Ref SamplingParamName
          - Name: API_TOKEN
            Type: PARAMETER_STORE
            Value: !Ref ApiTokenParamName

          - Name: REPOSITORY_NAME
            Type: PLAINTEXT
            Value: !Ref ArtifactRepositoryName
          - Name: PACKAGE_NAME
            Type: PLAINTEXT
            Value: !Ref AppName
          - Name: CFN_DOCGEN_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region

        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER 
      Name: !Sub ${AppName}-buildproject
      ServiceRole: !Ref BuildRole
      Source:
        ReportBuildStatus: true
        BuildSpec: ./buildspec.yaml
        Type: GITHUB
        Location: !Ref SourceURL
        Auth:
          Type: OAUTH
      Triggers:
        BuildType: BUILD
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/release
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
  NotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties: 
      DetailType: BASIC
      EventTypeIds: 
        - codebuild-project-build-state-failed
        - codebuild-project-build-state-succeeded
      Name: !Sub ${AppName}-build-result-notification
      Resource: !GetAtt BuildProject.Arn
      Status: ENABLED
      Targets: 
        - TargetType: SNS
          TargetAddress: !Ref SnsTopicArn
