AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: cfn-docgen-serverless
    Description: cfn-docgen automaticaly generate docs for templates that are stored in a specified s3 bucket
    Author: horietakehiro
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['cloudformation']
    HomePageUrl: https://github.com/horietakehiro/cfn-docgen
    SemanticVersion: #__VERSION__
    SourceCodeUrl: https://github.com/horietakehiro/cfn-docgen

# Parameters:
#   eventBucket:
#     Description: s3 bucket lambda function invokes
#     Type: String
  

Resources:
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource:
                  - !Sub arn:aws:s3:::cfn-docgen-${AWS::AccountId}-${AWS::Region}
                  - !Sub arn:aws:s3:::cfn-docgen-${AWS::AccountId}-${AWS::Region}/*
      Path: /

  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub cfn-docgen-${AWS::AccountId}-${AWS::Region}

  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.8
        - python3.9
      ContentUri: ./layer
      Description: cfn-docgen layer
      LayerName: cfn-docgen
      RetentionPolicy: Delete

  Function:
    # DependsOn:
    #   - Bucket
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./serverless
      Description: cfn docgen executor with s3
      Environment:
        Variables:
          HOME: "/tmp/"

      Events:
        JsonUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key: 
                Rules: 
                  - Name: prefix
                    Value: templates/
                  - Name: suffix
                    Value: .json
        YamlUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key: 
                Rules: 
                  - Name: prefix
                    Value: templates/
                  - Name: suffix
                    Value: .yaml
      FunctionName: cfn-docgen-serverless
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref Layer
      MemorySize: 1024
      PackageType: Zip
      # Policies:
      #   - Version: 2012-10-17
      #     Statement:
      #       - Effect: Allow
      #         Action: s3:*
      #         Resource:
      #           - !Sub arn:aws:s3:::cfn-docgen-${AWS::AccountId}-${AWS::Region}
      #           - !Sub arn:aws:s3:::cfn-docgen-${AWS::AccountId}-${AWS::Region}/*
      # - S3FullAccessPolicy:
      #     BucketName:
      #       Fn::Sub: cfn-docgen-${AWS::AccountId}-${AWS::Region}
      Runtime: python3.8
      Timeout: 600
      Role: !GetAtt FunctionRole.Arn
