AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  eventBucket:
    Description: s3 bucket lambda function invokes
    Type: String
  

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Ref eventBucket

  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.8
        - python3.9
      ContentUri: ./python
      Description: cfn-docgen layer
      LayerName: cfn-docgen
      RetentionPolicy: Delete

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./lambda
      Description: cfn docgen executor with s3
      Environment:
        Variables:
          HOME: "/tmp/"

      Events:
        JsonUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key: 
                Rules: 
                  - Name: prefix
                    Value: templates/
                  - Name: suffix
                    Value: .json
        YamlUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key: 
                Rules: 
                  - Name: prefix
                    Value: templates/
                  - Name: suffix
                    Value: .yaml
      FunctionName: cfn-docgen-serverless
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref Layer
      MemorySize: 1024
      PackageType: Zip
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref eventBucket
      Runtime: python3.8
      Timeout: 600
