Resources:
  CustomResource1:
    Type: Custom::Resource1
    Properties:
      ServiceToken: !GetAtt Function.Arn
      StringProp: string
      NestedProp:
        NumberProp: 0
        BoolProp: True
  CustomResource2:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt Function.Arn
      StringProp: string
      NestedProp:
        NumberProp: 0
        BoolProp: True
  Stack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        StringParam: string
        CommaDelimitedListParam:
          Fn::Join:
            - ","
            - 
              - item1
              - item2
      TemplateURL: https://bucket/prefix/template.yaml

